version: '3'
services:
  db:
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: coffee_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - coffee-network

  backend:
    build: ./backend
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp
    ports:
      - "8080:8080"
    networks:
      - coffee-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - coffee-network
    ports:
      - "3000:3000"

networks:
  coffee-network:
    driver: bridge

volumes:
  db:

